language: php

services:
  - postgresql

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

#before_install:
#  - phpenv config-rm xdebug.ini

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --dev --prefer-source --no-interaction

before_script:
  - psql -c 'create database karina_testing;' -U postgres
  - php artisan migrate

script:
  - vendor/bin/phpunit tests
